#' Assign individuals to groups based on 2-dimensional location and group size 
#'
#' This function clusters individuals into groups based on their locations and some mean group size. 
#' @param data list of simulation data generated by swap or UD method
#' @param id individual identifier field
#' @param xcoords x coordinates
#' @param ycoords y coordinates
#' @param time time step variable
#' @param group_size average group size in results
#' @param method grouping method, currently only hierarchical clustering implemented
#' @keywords group ids, cluster ids
#' @export
#' @examples
#' group_assign()

group_assign <- function(data = data,
                         id = "id",
                         xcoord = "x",
                         ycoord = "y",
                         time = "day",
                         group_size = 2,
                         method = "hclust") {
    lapply(data, function(w) {
      each_days_assoc <- lapply(w, function(x1) {
        num_clust <- ceiling(nrow(x1) / group_size)
        xc <- hclust(dist(x1[, c(xcoord, ycoord)]))
        groups <- cutree(xc, k = num_clust)
        daygroup <- cbind(x1, groups)
        rownames(daygroup) <- NULL
        return(daygroup)
      })
      eda <- do.call("rbind", each_days_assoc)
      eda$observation_id <- paste0(eda[,time], "_", eda$group)
      rownames(eda) <- NULL
      return(eda)
    })
  }
